project:
  type: website
  output-dir: docs

website:
  title: "BTS 510 <br> Summer 2024"
  sidebar:
    style: "docked" 
    search: true
    collapse-level: 1 
    contents:
      - index.qmd
      - syllabus.qmd  
      - schedule.qmd 
      - section: "Materials"
        contents:       
          - materials/index.qmd   
          - materials/00-mats.qmd
          - materials/01-mats.qmd 
          - materials/02-mats.qmd      
          - materials/03-mats.qmd
          - materials/04-mats.qmd
          - materials/05-mats.qmd
          - materials/06-mats.qmd  
          - materials/07-mats.qmd   
          - materials/08-mats.qmd 
          - materials/09-mats.qmd  
          - materials/10-mats.qmd  
          - materials/11-mats.qmd   
          - materials/12-mats.qmd 
          #- materials/13-mats.qmd 
      - section: "Complete labs"
        contents: 
          - labs_comp/index.qmd   
          - labs_comp/lab3.qmd   
          - labs_comp/lab4.qmd   
          - labs_comp/lab5.qmd
          - labs_comp/lab6.qmd   
          - labs_comp/lab7.qmd   
          - labs_comp/lab8.qmd 
          - labs_comp/lab9.qmd 
      - section: "Assignments"
        contents:
          - assignments/index.qmd    
          - assignments/hw1.qmd
          - assignments/hw2.qmd
          - assignments/hw3.qmd  
          - assignments/hw4.qmd            
          - assignments/hw5.qmd
          - assignments/final.qmd  
      - refs.qmd 
          
  # sidebar:
  #   - title: "Materials"
  #     style: "docked"
  #     contents:
  #       - section: materials/index.qmd
  #       - section: "Weekly materials"
  #         contents:
  #           - text: "Week 1: Introduction"
  #             file: materials/01-mats.qmd
  #           - text: "Week 2: Data manipulation"
  #             file: materials/02-mats.qmd
              
format:   
  html: 
    number-sections: false 
    theme: flatly
    css: styles.css
    toc: true



